name: vision
dependencies:
- matplotlib=1.5.1=np111py35_0
- nose=1.3.7=py35_1
- numpy=1.11.1=py35_0
- pillow=3.3.0=py35_0
- pip=8.1.2=py35_0
- python=3.5.2=0
- scikit-image=0.12.3=np111py35_1
- scikit-learn=0.17.1=np111py35_2
- scipy=0.17.1=np111py35_1
- statsmodels=0.6.1=np111py35_1
- pip:
  - nose-parameterized==0.5.0
  - peakutils==1.0.3
  - pyamg==3.0.2
  - sphinx==1.4.4
  - sphinx-rtd-theme==0.1.9
